# Generated by Django 4.2.6 on 2023-10-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_record_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='refered_by',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
