# Generated by Django 4.1.2 on 2023-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_record_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='item',
            field=models.CharField(default='Some dress', max_length=300),
        ),
    ]
