# Generated by Django 4.1.2 on 2023-10-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_record_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='advance_pay',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='balance',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='bicep',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='bottom',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='chest',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='culf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='fabric',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='final_payment',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='record',
            name='forearm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='full_crotch',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='full_sleeve_length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='half_sleeve_length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='hip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='jacket_length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='kurta_length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='mrp_total',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='natural_waist',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='neck',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='nehru_length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='shirt_length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='shoulder',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='thigh',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='trouser_length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='trouser_waist',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='waist_coat_length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='item',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
