from django.db import models

# Create your models here.
class Record(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(max_length=80)
    last_name =  models.CharField(max_length=80)
    email =  models.EmailField(max_length=80, null=True, blank=True)
    phone = models.CharField(max_length=80)
    address = models.CharField(max_length=80)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    zipcode = models.CharField(max_length=20)
    refered_by = models.CharField(max_length=40, null=True, blank=True)
    trial_date = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    delivery_date = models.DateField(auto_now_add = False, auto_now=False, null=True, blank=True)
    item = models.CharField(max_length=300, null=True, blank=True)
    fabric = models.CharField(max_length=60, null=True, blank=True)
    mrp_total = models.CharField(max_length=20, blank=True)
    advance_pay	= models.CharField(max_length=20, blank=True)
    balance	= models.CharField(max_length=20, blank=True)
    final_payment = models.CharField(max_length=30, blank=True)
    remarks = models.CharField(max_length=200, blank=True)
    neck = models.CharField(max_length=20, blank=True)
    shoulder = models.CharField(max_length=20, blank=True)
    chest = models.CharField(max_length=20, blank=True)
    natural_waist = models.CharField(max_length=20, blank=True) 
    trouser_waist = models.CharField(max_length=20, blank=True)
    hip = models.CharField(max_length=20, blank=True)
    bicep = models.CharField(max_length=20, blank=True)
    full_sleeve_length = models.CharField(max_length=20, blank=True)
    half_sleeve_length = models.CharField(max_length=20, blank=True)
    shirt_length = models.CharField(max_length=20, blank=True)
    jacket_length = models.CharField(max_length=20, blank=True)
    nehru_length = models.CharField(max_length=20, blank=True)
    waist_coat_length = models.CharField(max_length=20, blank=True)
    kurta_length = models.CharField(max_length=20, blank=True)
    trouser_length = models.CharField(max_length=20, blank=True)
    full_crotch	= models.CharField(max_length=20, blank=True) 
    thigh = models.CharField(max_length=20, blank=True) 
    bottom = models.CharField(max_length=20, blank=True) 

    def __str__(self):
        return (f"""{self.first_name} {self.last_name} """)
